### ISSUE TITLE
Implement "self test" functionality for firmware

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-firmware#12]
The control board has a "self test" button on it that is intended to perform hardware checks and report if there are any errors. It currently isn't setup to do anything, but we should write some code to make it functional.

Migrated from RoboJackets/robocup-software#633

**Comment by guyfleeman** [comment]
So this button is gone, can we close this? @jgkamat @petersonev

**Comment by petersonev** [comment]
Yup no button for it so closing
