### ISSUE TITLE
Re-enable robot rx/tx LEDs

### ISSUE THREAD

**Issue by jgkamat** [RoboJackets/robocup-firmware#19]
Justin disabled them in e8d59dd b/c something related to having too many timers seems to cause the mbed to crash and reboot.

Migrated from RoboJackets/robocup-software#745

**Comment by jgkamat** [comment]
@petersonev This can be closed correct? I think they're working now on the new radios.

**Comment by petersonev** [comment]
Probably but the LEDs on the radios behave a little differently and I need to make sure I can add another LED on the radio board before we know we don't need this. This definitely doesn't need to be priority high anymore at least
