### ISSUE TITLE
Update base station code.

### ISSUE THREAD

**Issue by jpfeltracco** [RoboJackets/robocup-firmware#38]
Base station code is currently broken on jon/stuff which will soon be in master.

**Comment by ashaw596** [comment]
I tried a simple fix by removing the led stuff from the constructor. But then the last parts of the packet the robot sends back started getting jumbled.

**Comment by jpfeltracco** [comment]
Was this just related to the packet size fix @petersonev? If so, I should just be able to remove that led stuff from the constructor and base station firmware should be working again right?
