### ISSUE TITLE
Fix Corruption at End of RTP Bot to Soccer Packet

### ISSUE THREAD

**Issue by jpfeltracco** [RoboJackets/robocup-firmware#50]

**Comment by guyfleeman** [comment]
@jpfeltracco got any ideas what's going on?

**Comment by guyfleeman** [comment]
@ashaw596 thanks for the info
@petersonev any updates?

**Comment by JNeiger** [comment]
I think this is still happening. When @jpfeltracco was implementing the encoder data forwarding to soccer, we had to add a [buffer](https://github.com/robojackets/robocup-fshare/compare/4defb667d02aeed1475be6b8db9b20420f7e4bd1...fc3b0524781967bd62dc2f4ee18fec6a4534b480#diff-f9f70a1c395cf8887effe02d2a2b9f80R112) at the end so the last encoder wouldn't get corrupted.

**Comment by guyfleeman** [comment]
@JNeiger so wait, you understand the issue?

**Comment by ashaw596** [comment]
Just looking through the code base a bit so not sure.
Could it be this line? Not sure whats its suppose to do but it was added a year ago.
The comment says its suppose to delete the last two elements. (Idk why though)
It actually deletes the 3rd and second to last elements and leaves the last elements.

` // remove the last 2 elements`
` buf.erase(buf.end() - 3, buf.end() - 1);`

https://github.com/RoboJackets/robocup-firmware/blob/d51a6d3b0b03ffa08991147a7b44068ad39fd75f/lib/drivers/decawave/Decawave.cpp#L139

**Comment by JNeiger** [comment]
@guyfleeman I'm not sure what is causing it. I just know that when we were doing the encoder forwarding, this issue popped up.

At the very least, if you remove that buffer value in the packet, it should be really easy to test if the problem still persists.

**Comment by guyfleeman** [comment]
@jneiger what branch is current for motion control data where we can try to reproduce?

**Comment by guyfleeman** [comment]
@ashaw596 good catch. I'll try to reproduce soon and see if modifying that line fixes it

**Comment by JNeiger** [comment]
@guyfleeman I don't think we made a specific branch to make testing the issue easy. The encoder stuff should already be on master. "Theoretically" just removing the buffer item from the packet should be enough to easily notice the problem when you print the encoder values to the console. 

These are the relevant PRs for this
https://github.com/RoboJackets/robocup-firmware/pull/55
https://github.com/RoboJackets/robocup-software/pull/1129
https://github.com/RoboJackets/robocup-fshare/pull/1

**Comment by jpfeltracco** [comment]
Yeah, just remove the dummy packet field called "buffer" or something and look at encoder 4 in the tree under the RX packet item. It won't make sense.
