### ISSUE TITLE
Mbed Firmware Has Poor Compiler Version Stability

### ISSUE THREAD

**Issue by guyfleeman** [RoboJackets/robocup-firmware#60]
We've seen issues with major compiler version upgrades causing failed arm builds, but the issue is getting worse in subtlety and debug difficulty. The only known good config indicates all firmware must be compiled on 18.04 (or try backporting Bionic's binutils to Xenial, see below).

With Jeremy's latest gyro control we've seen latent, strange, and detrimental compiler behavior. 16.04 generates binaries that immediately hardfault on a close() call. This is before other threads are created and we tried bumping stack size to no effect. Unpatched 18.04 and 17.10 simply generate unbootable binaries. 18.04 with 16.04 compiler and newlib, but 18.04 binutils generates stable binaries on all branches including gyro. 14.04 appeared to fail as well. To further complicate things, two 18.04 installs on identical pinned 16.04 compiler/newlib and 18.04 binutils generate, identical git hash, and same updated submodules generate binaries differing by 16 bytes. One machine was running mainline kernel instead of canonical-stable. It is unclear if this caused the difference. Both binaries ran stable for 150k+ packets. No bad binary made it past 10k+ packets without a hard fault.

Versions that successfully generating mbed binaries are becoming increasingly narrow. Info below:

**Known Good Configurations:**
_U18.04 (Bionic)_
gcc-arm-none-eabi: 4.9.3+svn231177-1 (Xenial)
libstdc++-arm-none-eabi-newlib: 4.9.3+svn227297-1+8 (Xenial)
libnewlib-arm-none-eabi: 2.2.0+git20150830.5a3d536-1 (Xenial)
libnewlib-dev: 2.2.0+git20150830.5a3d536-1 (Xenial)
binutils-arm-none-eabi: 2.27-9ubuntu1+9 (Bionic)
kernel: mainline-generic, 4.4.0-generic

**Known Bad Configurations:**
_U18.04 (Bionic) [mangled for all branches]_
gcc-arm-none-eabi: 6.3.1+svn253039-1build1 (Bionic)
libstdc++-arm-none-eabi-newlib: 6.3.1+svn253039-1+10 (Bionic)
libnewlib-arm-none-eabi: 2.4.0.20160527-3 (Bionic)
libnewlib-dev: 2.4.0.20160527-3 (Bionic)
binutils-arm-none-eabi: 2.27-9ubuntu1+9 (Bionic)
kernel: mainline-generic, 4.4.0-generic

_U17.10 (Artful) [mangled for all branches]_
gcc-arm-none-eabi: 5.4.1+svn241155-1 (Artful)
libstdc++-arm-none-eabi-newlib: 5.4.1+svn241155-1+9 (Artful)
libnewlib-arm-none-eabi: 2.4.0.20160527-2 (Artful)
libnewlib-dev: 2.4.0.20160527-2 (Artful)
binutils-arm-none-eabi: 2.27-9ubuntu1+9 (Artful//Bionic)
kernel: mainline-generic, 4.4.0-generic

_U16.04 (Xenial) [mangled for gyro control]_
gcc-arm-none-eabi: 4.9.3+svn231177-1 (Xenial)
libstdc++-arm-none-eabi-newlib: 4.9.3+svn227297-1+8 (Xenial)
libnewlib-arm-none-eabi: 2.2.0+git20150830.5a3d536-1 (Xenial)
libnewlib-dev: 2.2.0+git20150830.5a3d536-1 (Xenial)
binutils-arm-none-eabi: 2.26-4ubuntu1+8  (Xenial)
kernel: xenial-kernel-stable

_Jeremy's Arch Config [mangled for gyro control]_
gcc-arm-none-eabi: 8.x.x something?

_U14.04 (Trusty) [unclear but may be buggy]_
versions unconfirmed

At the end of the day, this is a strong reason to finish M-train.

**Comment by JNeiger** [comment]
rip mbed
